# Generated by Django 3.2 on 2021-10-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diastista',
            name='cep',
            field=models.CharField(max_length=8),
        ),
    ]
